apiVersion: apps/v1
kind: Deployment
metadata:
  name: httpd-frontend
spec:
  selector:
    matchLabels:
      name: mypod
  replicas: 3
  template:
    metadata:
      labels:
        name: mypod
    spec:
      containers:
        - name: mypod
          image: httpd:2.4-alpine